version: '3.8'

services:
  redis:
    image: "redis:7.4.5-alpine3.21"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - MODEL_PATH=${MODEL_PATH}
      - MODEL_N_CTX=${MODEL_N_CTX}
      - MODEL_N_THREADS=${MODEL_N_THREADS}
      - MODEL_MAXTOKEN=${MODEL_MAXTOKEN}

volumes:
  redis_data:
